### ISSUE TITLE
A Lit::to_i64 method would be useful

### ISSUE THREAD

**Issue by danielwaterworth** [Robbepop/dimacs-parser#1]
Currently, I have to resort to `transmute`.

**Comment by Robbepop** [comment]
Hi!

I think you can do `Lit::var().to_u64() as i64` to avoid unsafe code with the same effect.

**Comment by danielwaterworth** [comment]
That's not quite the same as, in the conversion to var, it applies `abs`. I know I can do it by applying the sign as well, but that seems like excess work when Lit contains exactly the value I want.

**Comment by danielwaterworth** [comment]
Btw, I appreciate you writing this. It's come in very handy for this year's end-of-year fun project.

**Comment by Robbepop** [comment]
You are right, and if you need it I will provide a `Lit::to_i64` method to receive its inner `i64` value without the `abs`.

**Comment by Robbepop** [comment]
Done with https://github.com/Robbepop/dimacs-parser/commit/a94d8096f334d2f717e19c95a8160b9629bc3c7b.

**Comment by danielwaterworth** [comment]
Excellent! Thank you
